import Foundation

/// Renders a set of `ScenarioResult`s as a self-contained, Apple-styled HTML report
/// (system font stack, Apple system colors, rounded cards, status pills, light/dark via
/// `prefers-color-scheme`). Pure string generation, no dependencies, so it is unit-testable
/// and the UI-test target can write it to disk after a scenario run.
public struct ScenarioReport: Sendable {
    public let title: String
    public let results: [ScenarioResult]
    public let generatedAt: Date

    public init(title: String, results: [ScenarioResult], generatedAt: Date = Date()) {
        self.title = title
        self.results = results
        self.generatedAt = generatedAt
    }

    public var passedCount: Int {
        results.filter(\.passed).count
    }

    public var allPassed: Bool {
        results.allSatisfy(\.passed)
    }

    public func html() -> String {
        let timestamp = Self.formatter.string(from: generatedAt)
        let summaryClass = allPassed ? "ok" : "fail"
        let summaryText = "\(passedCount) of \(results.count) scenarios passed"
        let cards = results.map(card).joined(separator: "\n")

        return """
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>\(escape(title))</title>
        <style>
        \(Self.css)
        </style>
        </head>
        <body>
        <main>
          <header class="hero">
            <h1>\(escape(title))</h1>
            <p class="subtitle">FlowSpec UI scenarios &middot; \(escape(timestamp))</p>
          </header>
          <section class="summary \(summaryClass)">
            <div class="count">\(passedCount)<span>/\(results.count)</span></div>
            <div class="summary-text">\(escape(summaryText))</div>
          </section>
          <section class="cards">
        \(cards)
          </section>
          <footer>Generated by FlowSpec &middot; Cupertino Desktop</footer>
        </main>
        </body>
        </html>
        """
    }

    private func card(_ result: ScenarioResult) -> String {
        let pill = result.passed ? "<span class=\"pill ok\">Passed</span>" : "<span class=\"pill fail\">Failed</span>"
        let duration = String(format: "%.1fs", result.duration)
        let failureBlock = result.failure.map { "<pre class=\"failure\">\(escape($0))</pre>" } ?? ""
        return """
            <article class="card \(result.passed ? "ok" : "fail")">
              <div class="card-head">
                \(pill)
                <h2>\(escape(result.title))</h2>
              </div>
              <div class="meta">
                <code>\(escape(result.id))</code>
                <span>\(result.stepCount) steps</span>
                <span>\(duration)</span>
              </div>
              \(failureBlock)
            </article>
        """
    }

    private func escape(_ text: String) -> String {
        text
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
    }

    private static let formatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        return formatter
    }()

    private static let css = """
    :root {
      --bg: #f5f5f7; --card: #ffffff; --text: #1d1d1f; --muted: #6e6e73;
      --ok: #34c759; --fail: #ff3b30; --line: rgba(0,0,0,0.08); --shadow: rgba(0,0,0,0.08);
    }
    @media (prefers-color-scheme: dark) {
      :root {
        --bg: #000000; --card: #1c1c1e; --text: #f5f5f7; --muted: #98989d;
        --line: rgba(255,255,255,0.10); --shadow: rgba(0,0,0,0.5);
      }
    }
    * { box-sizing: border-box; }
    body {
      margin: 0; background: var(--bg); color: var(--text);
      font-family: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Helvetica Neue", Helvetica, Arial, sans-serif;
      -webkit-font-smoothing: antialiased;
    }
    main { max-width: 760px; margin: 0 auto; padding: 48px 20px 64px; }
    .hero h1 { font-size: 40px; font-weight: 700; letter-spacing: -0.02em; margin: 0 0 6px; }
    .subtitle { color: var(--muted); font-size: 15px; margin: 0 0 28px; }
    .summary {
      display: flex; align-items: center; gap: 18px; background: var(--card);
      border-radius: 20px; padding: 24px 28px; margin-bottom: 24px;
      box-shadow: 0 2px 14px var(--shadow); border: 1px solid var(--line);
    }
    .summary .count { font-size: 44px; font-weight: 700; letter-spacing: -0.02em; }
    .summary .count span { font-size: 24px; color: var(--muted); font-weight: 600; }
    .summary.ok .count { color: var(--ok); }
    .summary.fail .count { color: var(--fail); }
    .summary-text { font-size: 18px; font-weight: 500; }
    .cards { display: grid; gap: 16px; }
    .card {
      background: var(--card); border-radius: 18px; padding: 20px 22px;
      box-shadow: 0 2px 12px var(--shadow); border: 1px solid var(--line);
    }
    .card-head { display: flex; align-items: center; gap: 12px; }
    .card-head h2 { font-size: 19px; font-weight: 600; margin: 0; }
    .pill {
      font-size: 12px; font-weight: 700; letter-spacing: 0.02em; text-transform: uppercase;
      padding: 4px 10px; border-radius: 999px; color: #fff; white-space: nowrap;
    }
    .pill.ok { background: var(--ok); }
    .pill.fail { background: var(--fail); }
    .meta { display: flex; gap: 16px; align-items: center; margin-top: 10px; color: var(--muted); font-size: 14px; }
    .meta code {
      font-family: "SF Mono", ui-monospace, Menlo, monospace; font-size: 13px;
      background: var(--bg); padding: 2px 8px; border-radius: 6px;
    }
    .failure {
      margin: 14px 0 0; padding: 14px 16px; border-radius: 12px;
      background: rgba(255,59,48,0.10); color: var(--fail);
      font-family: "SF Mono", ui-monospace, Menlo, monospace; font-size: 13px;
      white-space: pre-wrap; word-break: break-word;
    }
    footer { margin-top: 40px; text-align: center; color: var(--muted); font-size: 13px; }
    """
}
